---
title: "Basic Harvesting"
author: "William Lovejoy"
date: "7/6/2022"
output: html_document
---

```{r setup, warning=FALSE, message = FALSE}
library(rvest)
library(scales)
library(dplyr)
library(reshape2)
library(tidyverse)
```

  We'll load in these packages to scrape and handle our data.
  
```{r load page, warning=FALSE, message = FALSE}
base_webpage <- read_html("https://www.the-numbers.com/movie/budgets/all")
new_urls <- "https://www.the-numbers.com/movie/budgets/all/%s"
```


```{r, warning=FALSE, message = FALSE}
table_base <- html_table(base_webpage)[[1]] %>%
  as_tibble(.name_repair = "unique")
table_base
```


```{r pages, message=FALSE, error = FALSE}
table_new <- data.frame()
df <- data.frame()

i <- 101

while(i < 5502) {
  new_webpage <- read_html(sprintf(new_urls, i))
  table_new <- html_table(new_webpage)[[1]] %>%
    as_tibble(.name_repair = "unique")
  df <- rbind(df, table_new)
  i = i + 100
}

movies <- rbind(table_base, df)
glimpse(movies)
```

  This part iterates 5501 times to extract the data from the rest of the webpages
  
```{r cleaning, warning=FALSE, message = FALSE}
movies$ProductionBudget <- gsub("\\$|,", "", movies$ProductionBudget)
movies$DomesticGross <- gsub("\\$|,", "", movies$DomesticGross)
movies$WorldwideGross <- gsub("\\$|,", "", movies$WorldwideGross)
movies$ReleaseDate <- gsub(",", "", movies$ReleaseDate)

movies$ReleaseDate <- as.Date(as.character(movies$ReleaseDate), format = "%b %d %Y")
movies <- movies %>%
  mutate_at(c("ProductionBudget", "DomesticGross", "WorldwideGross"), as.numeric)

glimpse(movies)
write.csv(movies, 
          "C:\\Users\\William Lovejoy\\Documents\\Codes\\R\\DataScience\\movies.csv",
          row.names = FALSE)
```


```{r analysis, fig.width=6, warning=FALSE, message = FALSE}
movies %>%
  ggplot(aes(x = DomesticGross, y = WorldwideGross)) + geom_point() +
  geom_smooth() + scale_x_continuous(labels = label_number(prefix = "$", 
                                                           suffix = "M", 
                                                           scale = 1 / 1e6)) +
  scale_y_continuous(labels = label_number(prefix = "$", suffix = "B", 
                                           scale = 1 / 1e9)) + 
  labs(title = "Domestic vs. Gloabl Gross Movie Earnings", x = "Domestic", 
       y = "Global")

```

```{r fig2, fig.width=6, warning=FALSE, message = FALSE}
movies %>%
  ggplot(aes(x = ProductionBudget, y = WorldwideGross)) + geom_point()+
  geom_smooth() + scale_x_continuous(labels = label_number(prefix = "$", 
                                                           suffix = "M", 
                                                           scale = 1 / 1e6)) +
    scale_y_continuous(labels = label_number(prefix = "$", suffix = "B", 
                                           scale = 1 / 1e9)) + 
  labs(title = "Budget Vs. Global Gross Earnings", x = "Production Budget", 
       y = "Global Gross Earnings")
```



```{r correlate, fig.width=6, warning=FALSE, message = FALSE}
correlated <- movies[, -c(1:3)] %>%
  cor() %>%
  melt()

ggplot(correlated, aes(x = Var1, y = Var2, fill = value)) + 
  geom_tile(color = "black") +
  scale_fill_gradient2(low = "antiquewhite", mid = "gold", high = "firebrick") +
  geom_text(aes(label = round(value, 2)), size = 4) +
  theme(axis.text.x = element_text(angle = 90), axis.title = element_blank()) + 
  labs(title = "Correlation of Movies")
```



```{r, warning=FALSE, message = FALSE}
movies %>%
  ggplot(aes(x = ProductionBudget)) + geom_histogram() + 
  scale_x_continuous(labels = label_number(prefix = "$", suffix = "M", 
                                           scale = 1 / 1e6))
```


```{r, warning=FALSE, message = FALSE}
movies %>%
  ggplot(aes(x = ReleaseDate)) + geom_histogram() + 
  scale_x_date(limit = c(as.Date("1900-01-01"), as.Date("2022-07-06")),
               date_labels = "%Y", breaks = date_breaks("10 years")) +
  theme(axis.text.x = element_text(angle = 90)) + 
  labs(title = "Movie Release Dates Post 1900", x = "Release Date", y = "Count")
```







